version: 2
jobs:
  build:
    docker:
      - image: python:3

    steps:
      - checkout
      - run:
          name: Run unittest
          environment:
            PYTHONPATH: /root/project/v2/chapter3/
          command: |
            cd v2
            make testci